### ISSUE TITLE
Github Action not failing on found Issues

### ISSUE THREAD

**Issue by trifox** [carlosnizolli/RobotLint#1]
When the github action is executed and displays linter output, the workflow action is not failing, although return code of execution is not 0

**Comment by carlosnizolli** [comment]
The workflow fails when an error (E:) occurs, when an warning occurs the workflow does not fail.
![Screenshot_20211014-221010-791](https://user-images.githubusercontent.com/55762776/137416510-86ac6a75-5282-4161-b6b7-1d7af4e89b16.png)
